modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="mredstones"
version="1.0.0"
displayName="mredstones"
credits="https://discord.io/MoszkvaNetwork"
displayURL="https://discord.io/MoszkvaNetwork"
authors="nermanx"

[[dependencies.mredstones]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




